rm "images/image 3.png"
rm "images/works-bathy-02.webp"
rm "images/works-bathy-03.webp"
rm "images/works-bathy-04.webp"
rm "images/works-bathy-05.webp"
rm "images/works-bathy-06.webp"
rm "images/works-bathy-07.webp"
rm "images/works-firstpiece-01.webp"
rm "images/works-firstpiece-02.webp"
rm "images/works-firstpiece-03.webp"
rm "images/works-firstpiece-04.webp"
rm "images/works-firstpiece-05.webp"
rm "images/works-firstpiece-06.webp"
rm "images/works-firstpiece-07.webp"
rm "images/works-firstpiece-08.webp"
rm "images/works-firstpiece-09.webp"
rm "images/works-firstpiece-10.webp"